// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yqsyvbxeoqalddujghwh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlxc3l2Ynhlb3FhbGRkdWpnaHdoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyODAwMDMsImV4cCI6MjA1OTg1NjAwM30.fPwFNrMpM3gC-HrqFSeaU5SPW4if-BNR6pd0_FR_Dyc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);